server:
  port: 8082
  servlet:
    context-path: /api

spring:
  application:
    name:
      CloudLibrary
  servlet:
    multipart:
      max-file-size: 10MB
    # 为了限制 COS 云服务，使用local配置

  datasource:
    driver-class-name: com.mysql.cj.jdbc.Driver
    url: jdbc:mysql://localhost:3306/cloud
    username: root
    password: 12345678

  # Redis 配置
  redis:
    database: 0
    host: 127.0.0.1
    port: 6379
    timeout: 5000
  profiles:
    active: local

mybatis-plus:
  configuration:
    map-underscore-to-camel-case: false
    log-impl: org.apache.ibatis.logging.stdout.StdOutImpl
  global-config:
    db-config:
      logic-delete-field: isDelete
      logic-delete-value: 1
      logic-not-delete-value: 0


# 接口文档配置
knife4j:
  openapi:
    enable: true
    title: "接口文档"
    version: 1.0
    group:
      default:
        api-rule: package
        api-rule-resources:
          - com.anran.cloudlibrary.controller